/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersCreateRouteImport } from './routes/users-create'
import { Route as UsersUserIdRouteImport } from './routes/users-$userId'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'

const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users-create',
  path: '/users-create',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users-$userId',
  path: '/users-$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/users-$userId': typeof UsersUserIdRoute
  '/users-create': typeof UsersCreateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/users-$userId': typeof UsersUserIdRoute
  '/users-create': typeof UsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/users-$userId': typeof UsersUserIdRoute
  '/users-create': typeof UsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/users' | '/users-$userId' | '/users-create'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/users' | '/users-$userId' | '/users-create'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/users'
    | '/users-$userId'
    | '/users-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersCreateRoute: typeof UsersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users-create': {
      id: '/users-create'
      path: '/users-create'
      fullPath: '/users-create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-$userId': {
      id: '/users-$userId'
      path: '/users-$userId'
      fullPath: '/users-$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersCreateRoute: UsersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
